name: Publish .NET Global Tool

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build src/server/Sherlock.MCP.Server.csproj --configuration Release

    - name: Pack
      run: dotnet pack src/server/Sherlock.MCP.Server.csproj --configuration Release -o ./artifacts

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json